import type { LibraryItem } from "./types";

/**
 * Product template catalog. Add a new component by:
 * 1) appending an entry here
 * 2) adding a renderer in components/widgets/registry.tsx
 */
export const LIBRARY_CATALOG: LibraryItem[] = [
  // ── Process ──────────────────────────────────────────────
  {
    id: "tank",
    category: "process",
    name: "Tank",
    description: "Vertical process tank with animated level fill.",
    defaultWidth: 120,
    defaultHeight: 160,
    ports: [
      { id: "in-top", name: "Inlet", side: "top", offset: 0.5, direction: "in" },
      {
        id: "side-in",
        name: "Side in",
        side: "left",
        offset: 0.55,
        direction: "in",
      },
      {
        id: "out-bottom",
        name: "Outlet",
        side: "bottom",
        offset: 0.5,
        direction: "out",
      },
      {
        id: "side-out",
        name: "Side out",
        side: "right",
        offset: 0.55,
        direction: "out",
      },
    ],
    bindableProps: [
      { key: "level", label: "Level", dataType: "float", description: "0–100 %" },
    ],
    defaultProps: { label: "TANK-01", capacity: 100 },
  },
  {
    id: "vessel",
    category: "process",
    name: "Pressure Vessel",
    description: "Horizontal vessel / drum with level indication.",
    defaultWidth: 180,
    defaultHeight: 90,
    ports: [
      { id: "in", name: "Inlet", side: "left", offset: 0.5, direction: "in" },
      { id: "out", name: "Outlet", side: "right", offset: 0.5, direction: "out" },
      { id: "vent", name: "Vent", side: "top", offset: 0.5, direction: "out" },
    ],
    bindableProps: [{ key: "level", label: "Level", dataType: "float" }],
    defaultProps: { label: "V-01" },
  },
  {
    id: "valve",
    category: "process",
    name: "Valve",
    description: "On/off process valve.",
    defaultWidth: 72,
    defaultHeight: 72,
    ports: [
      { id: "a", name: "A", side: "left", offset: 0.5, direction: "bidirectional" },
      { id: "b", name: "B", side: "right", offset: 0.5, direction: "bidirectional" },
    ],
    bindableProps: [
      { key: "open", label: "Open", dataType: "bool" },
      { key: "position", label: "Position %", dataType: "float" },
    ],
    defaultProps: { label: "XV-01" },
  },
  {
    id: "control-valve",
    category: "process",
    name: "Control Valve",
    description: "Modulating valve with position stem.",
    defaultWidth: 80,
    defaultHeight: 96,
    ports: [
      { id: "a", name: "A", side: "left", offset: 0.65, direction: "bidirectional" },
      { id: "b", name: "B", side: "right", offset: 0.65, direction: "bidirectional" },
    ],
    bindableProps: [{ key: "position", label: "Position %", dataType: "float" }],
    defaultProps: { label: "FV-01" },
  },
  {
    id: "check-valve",
    category: "process",
    name: "Check Valve",
    description: "One-way check valve symbol.",
    defaultWidth: 64,
    defaultHeight: 56,
    ports: [
      { id: "a", name: "In", side: "left", offset: 0.5, direction: "in" },
      { id: "b", name: "Out", side: "right", offset: 0.5, direction: "out" },
    ],
    bindableProps: [],
    defaultProps: { label: "CV-01" },
  },
  {
    id: "pump",
    category: "process",
    name: "Pump",
    description: "Centrifugal pump with running status.",
    defaultWidth: 96,
    defaultHeight: 80,
    ports: [
      { id: "suction", name: "Suction", side: "left", offset: 0.5, direction: "in" },
      {
        id: "discharge",
        name: "Discharge",
        side: "right",
        offset: 0.5,
        direction: "out",
      },
    ],
    bindableProps: [{ key: "running", label: "Running", dataType: "bool" }],
    defaultProps: { label: "P-01" },
  },
  {
    id: "blower",
    category: "process",
    name: "Blower / Fan",
    description: "Air blower with running animation.",
    defaultWidth: 100,
    defaultHeight: 88,
    ports: [
      { id: "in", name: "Inlet", side: "left", offset: 0.5, direction: "in" },
      { id: "out", name: "Outlet", side: "right", offset: 0.5, direction: "out" },
    ],
    bindableProps: [{ key: "running", label: "Running", dataType: "bool" }],
    defaultProps: { label: "B-01" },
  },
  {
    id: "compressor",
    category: "process",
    name: "Compressor",
    description: "Gas compressor block.",
    defaultWidth: 110,
    defaultHeight: 90,
    ports: [
      { id: "in", name: "Inlet", side: "left", offset: 0.5, direction: "in" },
      { id: "out", name: "Outlet", side: "right", offset: 0.5, direction: "out" },
    ],
    bindableProps: [
      { key: "running", label: "Running", dataType: "bool" },
      { key: "load", label: "Load %", dataType: "float" },
    ],
    defaultProps: { label: "K-01" },
  },
  {
    id: "motor",
    category: "process",
    name: "Motor",
    description: "Motor / drive status block.",
    defaultWidth: 100,
    defaultHeight: 72,
    ports: [],
    bindableProps: [
      { key: "running", label: "Running", dataType: "bool" },
      { key: "speed", label: "Speed", dataType: "float" },
    ],
    defaultProps: { label: "M-01" },
  },
  {
    id: "heat-exchanger",
    category: "process",
    name: "Heat Exchanger",
    description: "Shell-and-tube style exchanger.",
    defaultWidth: 140,
    defaultHeight: 100,
    ports: [
      { id: "hot-in", name: "Hot in", side: "left", offset: 0.3, direction: "in" },
      { id: "hot-out", name: "Hot out", side: "right", offset: 0.3, direction: "out" },
      { id: "cold-in", name: "Cold in", side: "left", offset: 0.7, direction: "in" },
      {
        id: "cold-out",
        name: "Cold out",
        side: "right",
        offset: 0.7,
        direction: "out",
      },
    ],
    bindableProps: [{ key: "duty", label: "Duty %", dataType: "float" }],
    defaultProps: { label: "HE-01" },
  },
  {
    id: "filter",
    category: "process",
    name: "Filter",
    description: "Inline process filter.",
    defaultWidth: 88,
    defaultHeight: 72,
    ports: [
      { id: "in", name: "Inlet", side: "left", offset: 0.5, direction: "in" },
      { id: "out", name: "Outlet", side: "right", offset: 0.5, direction: "out" },
    ],
    bindableProps: [{ key: "dp", label: "ΔP", dataType: "float" }],
    defaultProps: { label: "F-01" },
  },
  {
    id: "reactor",
    category: "process",
    name: "Reactor",
    description: "Stirred reactor vessel.",
    defaultWidth: 130,
    defaultHeight: 150,
    ports: [
      { id: "in-top", name: "Feed", side: "top", offset: 0.5, direction: "in" },
      {
        id: "in-left",
        name: "Side feed",
        side: "left",
        offset: 0.35,
        direction: "in",
      },
      {
        id: "in-left-lo",
        name: "Side feed lo",
        side: "left",
        offset: 0.65,
        direction: "in",
      },
      {
        id: "out-bottom",
        name: "Product",
        side: "bottom",
        offset: 0.5,
        direction: "out",
      },
      {
        id: "out-right",
        name: "Side out",
        side: "right",
        offset: 0.5,
        direction: "out",
      },
    ],
    bindableProps: [
      { key: "level", label: "Level", dataType: "float" },
      { key: "temp", label: "Temp", dataType: "float" },
      { key: "agitating", label: "Agitating", dataType: "bool" },
    ],
    defaultProps: { label: "R-01" },
  },
  {
    id: "conveyor",
    category: "process",
    name: "Conveyor",
    description: "Belt conveyor with run status.",
    defaultWidth: 200,
    defaultHeight: 56,
    ports: [
      { id: "in", name: "In", side: "left", offset: 0.5, direction: "in" },
      { id: "out", name: "Out", side: "right", offset: 0.5, direction: "out" },
    ],
    bindableProps: [{ key: "running", label: "Running", dataType: "bool" }],
    defaultProps: { label: "CVY-01" },
  },

  // ── Indicators ───────────────────────────────────────────
  {
    id: "gauge",
    category: "indicators",
    name: "Analog Gauge",
    description: "Circular gauge for pressure, flow, or level.",
    defaultWidth: 110,
    defaultHeight: 110,
    ports: [],
    bindableProps: [{ key: "value", label: "Value", dataType: "float" }],
    defaultProps: { label: "PI-01", min: 0, max: 100, unit: "bar" },
  },
  {
    id: "numeric",
    category: "indicators",
    name: "Numeric Display",
    description: "Large process value readout.",
    defaultWidth: 140,
    defaultHeight: 56,
    ports: [],
    bindableProps: [{ key: "value", label: "Value", dataType: "float" }],
    defaultProps: { label: "PV", decimals: 1, unit: "" },
  },
  {
    id: "lamp",
    category: "indicators",
    name: "Status Lamp",
    description: "Boolean status indicator.",
    defaultWidth: 64,
    defaultHeight: 64,
    ports: [],
    bindableProps: [{ key: "on", label: "On", dataType: "bool" }],
    defaultProps: { label: "HS", colorOn: "#3ddc97", colorOff: "#2a3340" },
  },
  {
    id: "bar",
    category: "indicators",
    name: "Bar Graph",
    description: "Vertical bar for level or analog.",
    defaultWidth: 48,
    defaultHeight: 140,
    ports: [],
    bindableProps: [{ key: "value", label: "Value", dataType: "float" }],
    defaultProps: { label: "LI", min: 0, max: 100 },
  },
  {
    id: "text",
    category: "indicators",
    name: "Text Label",
    description: "Static or bound text annotation on a screen.",
    defaultWidth: 160,
    defaultHeight: 32,
    ports: [],
    bindableProps: [{ key: "text", label: "Text", dataType: "string" }],
    defaultProps: { label: "Label", fontSize: 14, color: "#e8eef7" },
  },
  {
    id: "sparkline",
    category: "indicators",
    name: "Sparkline Trend",
    description: "Mini live trend strip.",
    defaultWidth: 160,
    defaultHeight: 64,
    ports: [],
    bindableProps: [{ key: "value", label: "Value", dataType: "float" }],
    defaultProps: { label: "TR-01", min: 0, max: 100 },
  },
  {
    id: "alarm-banner",
    category: "indicators",
    name: "Alarm Banner",
    description: "Active alarm / warning strip.",
    defaultWidth: 220,
    defaultHeight: 48,
    ports: [],
    bindableProps: [
      { key: "active", label: "Active", dataType: "bool" },
      { key: "text", label: "Text", dataType: "string" },
    ],
    defaultProps: { label: "ALARM", message: "High level" },
  },

  // ── Controls ─────────────────────────────────────────────
  {
    id: "button",
    category: "controls",
    name: "Push Button",
    description: "Momentary / toggle control (sim write).",
    defaultWidth: 96,
    defaultHeight: 48,
    ports: [],
    bindableProps: [{ key: "pressed", label: "Pressed", dataType: "bool" }],
    defaultProps: { label: "START", mode: "momentary" },
  },
  {
    id: "toggle",
    category: "controls",
    name: "Toggle Switch",
    description: "Maintained boolean control.",
    defaultWidth: 88,
    defaultHeight: 48,
    ports: [],
    bindableProps: [{ key: "state", label: "State", dataType: "bool" }],
    defaultProps: { label: "AUTO" },
  },
  {
    id: "setpoint",
    category: "controls",
    name: "Setpoint Entry",
    description: "Numeric setpoint display / entry stub.",
    defaultWidth: 130,
    defaultHeight: 64,
    ports: [],
    bindableProps: [{ key: "value", label: "SP", dataType: "float" }],
    defaultProps: { label: "SP", unit: "%" },
  },
  {
    id: "selector",
    category: "controls",
    name: "Mode Selector",
    description: "MAN / AUTO mode selector.",
    defaultWidth: 120,
    defaultHeight: 52,
    ports: [],
    bindableProps: [{ key: "auto", label: "Auto", dataType: "bool" }],
    defaultProps: { label: "MODE" },
  },

  // ── Faceplates ───────────────────────────────────────────
  {
    id: "pid-face",
    category: "faces",
    name: "PID Faceplate",
    description: "Compact PV / SP / OUT faceplate.",
    defaultWidth: 160,
    defaultHeight: 120,
    ports: [],
    bindableProps: [
      { key: "pv", label: "PV", dataType: "float" },
      { key: "sp", label: "SP", dataType: "float" },
      { key: "out", label: "OUT", dataType: "float" },
    ],
    defaultProps: { label: "PIC-101", unit: "%" },
  },
  {
    id: "motor-face",
    category: "faces",
    name: "Motor Faceplate",
    description: "Motor start/stop, speed, and amps.",
    defaultWidth: 180,
    defaultHeight: 140,
    ports: [],
    bindableProps: [
      { key: "running", label: "Running", dataType: "bool" },
      { key: "speed", label: "Speed", dataType: "float" },
      { key: "amps", label: "Amps", dataType: "float" },
      { key: "fault", label: "Fault", dataType: "bool" },
    ],
    defaultProps: { label: "MTR-101" },
  },
  {
    id: "pump-face",
    category: "faces",
    name: "Pump Faceplate",
    description: "Pump run, flow, and pressure.",
    defaultWidth: 180,
    defaultHeight: 140,
    ports: [],
    bindableProps: [
      { key: "running", label: "Running", dataType: "bool" },
      { key: "flow", label: "Flow", dataType: "float" },
      { key: "pressure", label: "Pressure", dataType: "float" },
      { key: "fault", label: "Fault", dataType: "bool" },
    ],
    defaultProps: { label: "PMP-101", flowUnit: "m³/h", pressureUnit: "bar" },
  },
  {
    id: "valve-face",
    category: "faces",
    name: "Valve Faceplate",
    description: "Open/close command and position feedback.",
    defaultWidth: 170,
    defaultHeight: 130,
    ports: [],
    bindableProps: [
      { key: "open", label: "Open FB", dataType: "bool" },
      { key: "position", label: "Position", dataType: "float" },
      { key: "fault", label: "Fault", dataType: "bool" },
    ],
    defaultProps: { label: "VLV-101" },
  },
  {
    id: "tank-face",
    category: "faces",
    name: "Tank Faceplate",
    description: "Level with Hi / Lo alarm indicators.",
    defaultWidth: 170,
    defaultHeight: 150,
    ports: [],
    bindableProps: [
      { key: "level", label: "Level", dataType: "float" },
      { key: "hi", label: "Hi alarm", dataType: "bool" },
      { key: "lo", label: "Lo alarm", dataType: "bool" },
    ],
    defaultProps: { label: "TK-101", unit: "%" },
  },
  {
    id: "vfd-face",
    category: "faces",
    name: "VFD Faceplate",
    description: "Variable frequency drive status.",
    defaultWidth: 180,
    defaultHeight: 150,
    ports: [],
    bindableProps: [
      { key: "running", label: "Running", dataType: "bool" },
      { key: "hz", label: "Frequency", dataType: "float" },
      { key: "amps", label: "Amps", dataType: "float" },
      { key: "torque", label: "Torque %", dataType: "float" },
    ],
    defaultProps: { label: "VFD-101" },
  },
  {
    id: "temp-face",
    category: "faces",
    name: "Temperature Faceplate",
    description: "PV / SP temperature controller face.",
    defaultWidth: 170,
    defaultHeight: 130,
    ports: [],
    bindableProps: [
      { key: "pv", label: "PV", dataType: "float" },
      { key: "sp", label: "SP", dataType: "float" },
      { key: "out", label: "OUT", dataType: "float" },
    ],
    defaultProps: { label: "TIC-101", unit: "°C" },
  },
  {
    id: "flow-face",
    category: "faces",
    name: "Flow Faceplate",
    description: "Flow totalizer / rate faceplate.",
    defaultWidth: 170,
    defaultHeight: 120,
    ports: [],
    bindableProps: [
      { key: "rate", label: "Rate", dataType: "float" },
      { key: "total", label: "Total", dataType: "float" },
    ],
    defaultProps: { label: "FIC-101", rateUnit: "m³/h", totalUnit: "m³" },
  },
];

export function getLibraryItem(id: string): LibraryItem | undefined {
  return LIBRARY_CATALOG.find((item) => item.id === id);
}

export const CATEGORY_LABELS: Record<LibraryItem["category"], string> = {
  process: "Process",
  indicators: "Indicators",
  controls: "Controls",
  faces: "Faceplates",
};
