import type { OpcUaConfig, ProjectState, Screen, Tag } from "./types";

function id(prefix: string) {
  return `${prefix}_${crypto.randomUUID().slice(0, 8)}`;
}

export function createDefaultOpcUa(): OpcUaConfig {
  return {
    endpointUrl: "opc.tcp://192.168.1.10:4840",
    securityMode: "None",
    securityPolicy: "None",
    authMode: "Anonymous",
    username: "",
    password: "",
    enabled: false,
    pollIntervalMs: 500,
    mappings: [],
    status: {
      state: "disconnected",
      message: "Not connected — Phase 1 uses simulation only.",
    },
  };
}

export function createSeedTags(): Tag[] {
  const now = Date.now();
  return [
    {
      id: "tag_tank_level",
      name: "Tank_Level",
      path: "Plant.Area1.Tank01.Level",
      dataType: "float",
      unit: "%",
      description: "Primary tank level",
      value: 62,
      quality: "good",
      timestamp: now,
      source: "simulation",
      sim: {
        profile: "sine",
        periodMs: 12000,
        min: 15,
        max: 92,
        amplitude: 30,
        offset: 55,
        phase: 0,
      },
      hiLimit: 85,
      loLimit: 20,
    },
    {
      id: "tag_pump_run",
      name: "Pump_Running",
      path: "Plant.Area1.P01.Running",
      dataType: "bool",
      description: "Feed pump status",
      value: true,
      quality: "good",
      timestamp: now,
      source: "simulation",
      sim: {
        profile: "toggle",
        periodMs: 7000,
        min: 0,
        max: 1,
        amplitude: 1,
        offset: 0,
        phase: 0,
      },
    },
    {
      id: "tag_valve_open",
      name: "Valve_Open",
      path: "Plant.Area1.XV01.Open",
      dataType: "bool",
      value: false,
      quality: "good",
      timestamp: now,
      source: "simulation",
      sim: {
        profile: "pulse",
        periodMs: 5000,
        min: 0,
        max: 1,
        amplitude: 1,
        offset: 0,
        phase: 0.2,
      },
    },
    {
      id: "tag_pressure",
      name: "Line_Pressure",
      path: "Plant.Area1.PI01.PV",
      dataType: "float",
      unit: "bar",
      value: 4.2,
      quality: "good",
      timestamp: now,
      source: "simulation",
      sim: {
        profile: "noise",
        periodMs: 6000,
        min: 2,
        max: 8,
        amplitude: 1.5,
        offset: 4.5,
        phase: 1,
      },
    },
    {
      id: "tag_flow",
      name: "Flow_Rate",
      path: "Plant.Area1.FI01.PV",
      dataType: "float",
      unit: "m³/h",
      value: 28,
      quality: "good",
      timestamp: now,
      source: "simulation",
      sim: {
        profile: "ramp",
        periodMs: 15000,
        min: 5,
        max: 45,
        amplitude: 20,
        offset: 25,
        phase: 0,
      },
    },
    {
      id: "tag_motor_speed",
      name: "Motor_Speed",
      path: "Plant.Area1.M01.Speed",
      dataType: "float",
      unit: "rpm",
      value: 1450,
      quality: "good",
      timestamp: now,
      source: "simulation",
      sim: {
        profile: "sine",
        periodMs: 9000,
        min: 800,
        max: 1800,
        amplitude: 400,
        offset: 1300,
        phase: 0.5,
      },
    },
    {
      id: "tag_pid_pv",
      name: "PIC101_PV",
      path: "Plant.Area1.PIC101.PV",
      dataType: "float",
      unit: "%",
      value: 48,
      quality: "good",
      timestamp: now,
      source: "simulation",
      sim: {
        profile: "sine",
        periodMs: 10000,
        min: 30,
        max: 70,
        amplitude: 15,
        offset: 50,
        phase: 0,
      },
    },
    {
      id: "tag_pid_sp",
      name: "PIC101_SP",
      path: "Plant.Area1.PIC101.SP",
      dataType: "float",
      unit: "%",
      value: 50,
      quality: "good",
      timestamp: now,
      source: "simulation",
      sim: {
        profile: "constant",
        periodMs: 1000,
        min: 0,
        max: 100,
        amplitude: 0,
        offset: 50,
        phase: 0,
      },
    },
    {
      id: "tag_pid_out",
      name: "PIC101_OUT",
      path: "Plant.Area1.PIC101.OUT",
      dataType: "float",
      unit: "%",
      value: 42,
      quality: "good",
      timestamp: now,
      source: "simulation",
      sim: {
        profile: "sine",
        periodMs: 10000,
        min: 20,
        max: 80,
        amplitude: 20,
        offset: 45,
        phase: 1.2,
      },
    },
    {
      id: "tag_hs_ready",
      name: "System_Ready",
      path: "Plant.Area1.HS.Ready",
      dataType: "bool",
      value: true,
      quality: "good",
      timestamp: now,
      source: "simulation",
      sim: {
        profile: "constant",
        periodMs: 1000,
        min: 0,
        max: 1,
        amplitude: 0,
        offset: 1,
        phase: 0,
      },
    },
  ];
}

export function createDemoScreen(): Screen {
  const tankId = id("obj");
  const pumpId = id("obj");
  const valveId = id("obj");
  const gaugeId = id("obj");
  const numericId = id("obj");
  const lampId = id("obj");
  const pidId = id("obj");
  const motorId = id("obj");

  return {
    id: id("scr"),
    name: "Area 1 — Feed Line",
    width: 1280,
    height: 720,
    objects: [
      {
        id: tankId,
        libraryItemId: "tank",
        name: "TANK-01",
        x: 120,
        y: 180,
        width: 140,
        height: 200,
        rotation: 0,
        bindings: [{ prop: "level", tagId: "tag_tank_level" }],
        props: { label: "TANK-01", capacity: 100 },
      },
      {
        id: pumpId,
        libraryItemId: "pump",
        name: "P-01",
        x: 360,
        y: 300,
        width: 110,
        height: 90,
        rotation: 0,
        bindings: [{ prop: "running", tagId: "tag_pump_run" }],
        props: { label: "P-01" },
      },
      {
        id: valveId,
        libraryItemId: "valve",
        name: "XV-01",
        x: 540,
        y: 310,
        width: 80,
        height: 80,
        rotation: 0,
        bindings: [{ prop: "open", tagId: "tag_valve_open" }],
        props: { label: "XV-01" },
      },
      {
        id: gaugeId,
        libraryItemId: "gauge",
        name: "PI-01",
        x: 700,
        y: 120,
        width: 120,
        height: 120,
        rotation: 0,
        bindings: [{ prop: "value", tagId: "tag_pressure" }],
        props: { label: "PI-01", min: 0, max: 10, unit: "bar" },
      },
      {
        id: numericId,
        libraryItemId: "numeric",
        name: "FI-01",
        x: 700,
        y: 280,
        width: 150,
        height: 60,
        rotation: 0,
        bindings: [{ prop: "value", tagId: "tag_flow" }],
        props: { label: "Flow", decimals: 1, unit: "m³/h" },
      },
      {
        id: lampId,
        libraryItemId: "lamp",
        name: "Ready",
        x: 900,
        y: 140,
        width: 70,
        height: 70,
        rotation: 0,
        bindings: [{ prop: "on", tagId: "tag_hs_ready" }],
        props: { label: "READY", colorOn: "#3ddc97", colorOff: "#2a3340" },
      },
      {
        id: motorId,
        libraryItemId: "motor",
        name: "M-01",
        x: 880,
        y: 280,
        width: 110,
        height: 80,
        rotation: 0,
        bindings: [
          { prop: "running", tagId: "tag_pump_run" },
          { prop: "speed", tagId: "tag_motor_speed" },
        ],
        props: { label: "M-01" },
      },
      {
        id: pidId,
        libraryItemId: "pid-face",
        name: "PIC-101",
        x: 1040,
        y: 200,
        width: 170,
        height: 130,
        rotation: 0,
        bindings: [
          { prop: "pv", tagId: "tag_pid_pv" },
          { prop: "sp", tagId: "tag_pid_sp" },
          { prop: "out", tagId: "tag_pid_out" },
        ],
        props: { label: "PIC-101", unit: "%" },
      },
    ],
    connections: [
      {
        id: id("conn"),
        from: { objectId: tankId, portId: "out-bottom" },
        to: { objectId: pumpId, portId: "suction" },
      },
      {
        id: id("conn"),
        from: { objectId: pumpId, portId: "discharge" },
        to: { objectId: valveId, portId: "a" },
      },
    ],
  };
}

export function createInitialProject(): ProjectState {
  const screen = createDemoScreen();
  return {
    name: "SCADA One Demo",
    version: 1,
    tags: createSeedTags(),
    screens: [screen],
    activeScreenId: screen.id,
    runtimeScreenId: screen.id,
    opcUa: createDefaultOpcUa(),
    selectedObjectId: null,
    connectFrom: null,
    designerMode: "select",
    simRunning: true,
    simTickMs: 500,
  };
}

export { id as newId };
